language: objective-c
osx_image: xcode8.2

before_install:
  - echo $TRAVIS_OS_NAME
  - echo $LANG
  - echo $LC_ALL
  - brew install xcproj

install: true

script:
  - mkdir osx && cd osx
  - cmake -DCMAKE_TOOLCHAIN_FILE=../core/CMake/OSXToolchain.cmake ..
  - make flatc
  - cd ..
  - mkdir ios && cd ios
  - cmake -GXcode -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=../core/CMake/iOSToolchain.cmake ..
  - mkdir -p Project.xcodeproj/xcshareddata/xcschemes
  - cp ../LTerminal.xcscheme Project.xcodeproj/xcshareddata/xcschemes
  - cp ../Podfile .
  - xcproj touch Project.xcodeproj
  - ../core/CMake/AddInheritedVariablesToXCodeproj.rb
  - pod install
  - xcodebuild -scheme LTerminal -workspace Project.xcworkspace -configuration Release

after_success:
  - echo "success"

after_failure:
  - echo "failure"
