desc "Build and submit to TestFlight"
lane :submit_testflight do
  
  keychain_name = "testflight_certs"
  delete_keychain(
    name: keychain_name,
  )

  create_keychain(
    name: keychain_name,
    default_keychain: true,
    unlock: true,
    timeout: 3600,
    lock_when_sleeps: true,
    password: SecureRandom.base64
  )
  
  import_certificate(
    certificate_path: "fastlane/Certificates/distribution.p12",
    certificate_password: ENV["KEY_PASSWORD"],
    keychain_name: keychain_name
  )
 
  sigh(
    username: "jmfoutts@gmail.com",
    provisioning_name: "LTerminal Distribution",
    team_id: "9S723G94YQ",
    cert_id: "37FZJG96GW"
  )
  
  gym(
    clean: true,
    project: "ios/Project.xcodeproj",
    scheme: "LTerminal",
    configuration: "Release",
    output_name: "LTerminal.ipa",
    export_method: "enterprise",
    include_bitcode: false,
    include_symbols: false,
    use_legacy_build_api: true,
  )
  
  # pilot(username: "your_app_id_username")

  delete_keychain(
    name: keychain_name,
  )
end
